apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-1
spec:
  template:
    spec:
      tolerations:
      - key: "onlyprocess"
        operator: "Equal"
        value: "gpu"        
        effect: "NoExecute"