apiVersion: v1
kind: Service
metadata:
  name: test-svc    
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8100
      targetPort: 80
      name: web
  selector:
    app: ingress-test
  type: ClusterIP